query failed error at order-watcher
shinonome-inc/0x-order-watcher pull request #19
Opened 2023-01-11 08:11 UTC by takakuda

https://www.notion.so/shinonome-inc/query-failed-error-at-order-watcher-1fe2ca2168e14478b7d8544d614c34bd

hashがユニークなものであるかどうかを確認するロジックを追加しました。

2023-01-11 08:12 UTC, takakuda commented on src/order_watcher.ts
> +                const order = await this._connection.getRepository(SignedOrderV4Entity).findOne({ hash: entity.hash })
同一hashのorderが存在するかどうかのcheckを追加しています。同一orderが存在した場合はvalidOrderEntitiesにpushしないようにしています。

2023-01-12 08:35 UTC, massun-onibakuchi requested changes
確認お願いします

2023-01-12 08:35 UTC, massun-onibakuchi commented on src/order_watcher.ts
> +            const i = parseInt(index, 10)
question： parseIntするのはなぜですか？

2023-01-12 08:35 UTC, massun-onibakuchi commented on src/order_watcher.ts
> +                const order = await this._connection.getRepository(SignedOrderV4Entity).findOne({ hash: entity.hash })
question:219行目から同じような処理を行っているのはミスですか？

2023-01-12 08:35 UTC, massun-onibakuchi commented on src/order_watcher.ts
> +                }
ここでDBに既にある注文データの更新を行いたいので、単に「同一orderが存在した場合はvalidOrderEntitiesにpushしないようにする」と、それが機能しなくなってしまいます。
https://github.com/shinonome-inc/0x-order-watcher/blob/a7e60f696a10f27c808d78875768ac4056878fd3/src/order_watcher.ts#L89-L93

データの一部を更新する処理
https://github.com/shinonome-inc/0x-order-watcher/blob/a7e60f696a10f27c808d78875768ac4056878fd3/src/order_watcher.ts#L94-L104

2023-01-12 09:47 UTC, takakuda commented on src/order_watcher.ts
> +                }
@massun-onibakuchi 
そうなると`postOrdersAsync`の場合のみ同一orderは省くという処理にするべきでしょうか？

2023-01-13 07:01 UTC, closed without merging